name: VoiceGenius
options:
  bundleIdPrefix: com.voicegenius
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false

targets:
  VoiceGenius:
    type: application
    platform: iOS
    sources:
      - VoiceGenius
      - path: config.json
        type: file
        buildPhase: resources
    preBuildScripts:
      - name: Start Sidecar (Simulator Only)
        script: |
          # Only run for Simulator builds
          if [[ "$PLATFORM_NAME" == "iphonesimulator" ]]; then
            SIDECAR_DIR="${SRCROOT}/sidecar"
            SIDECAR_LOG="/tmp/voicegenius_sidecar.log"

            # Check if sidecar is already running on port 8080
            if lsof -i :8080 -sTCP:LISTEN > /dev/null 2>&1; then
              echo "✅ Sidecar already running on port 8080"
              exit 0
            fi

            # Check if Python dependencies are installed
            # Use python3.12 explicitly since packages are installed there
            PYTHON="/opt/homebrew/bin/python3.12"
            if ! $PYTHON -c "import flask, mlx_lm" 2>/dev/null; then
              echo "⚠️ Python dependencies not installed. Run:"
              echo "   cd ${SIDECAR_DIR} && pip install -r requirements.txt"
              echo ""
              echo "Note: First run will download ~700MB model from HuggingFace"
              exit 0
            fi

            echo "🚀 Starting sidecar server..."
            cd "$SIDECAR_DIR"
            nohup $PYTHON sidecar.py > "$SIDECAR_LOG" 2>&1 &

            # Wait for server to be ready (model loading takes time)
            echo "⏳ Waiting for model to load (this may take 30-60s on first run)..."
            for i in {1..60}; do
              if lsof -i :8080 -sTCP:LISTEN > /dev/null 2>&1; then
                echo "✅ Sidecar ready on port 8080"
                exit 0
              fi
              sleep 1
            done

            echo "⚠️ Sidecar still loading... check: tail -f $SIDECAR_LOG"
          fi
        basedOnDependencyAnalysis: false
    settings:
      base:
        INFOPLIST_FILE: VoiceGenius/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.voicegenius.app
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: VoiceGenius/Info.plist
      properties:
        CFBundleDisplayName: VoiceGenius
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        UILaunchStoryboardName: LaunchScreen
        NSMicrophoneUsageDescription: "VoiceGenius needs microphone access to hear your voice."
        NSSpeechRecognitionUsageDescription: "VoiceGenius uses speech recognition to convert your voice to text."
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIBackgroundModes:
          - audio
